---
language: python
services:
- docker

python:
- "3.6"

env:
- OPENCV_VERSION=3.4.1

before_install:
- export IMAGE=jjanzic/docker-python3-opencv:opencv-$OPENCV_VERSION
- docker pull $IMAGE
- docker run $IMAGE pip --version

script:
- python setup.py sdist
- docker run --mount type=bind,source="$(pwd)"/dist,target=/dist $IMAGE /bin/sh -c "pip install pybind11 && pip install /$(echo dist/*.tar.gz) && python -c 'import cscore'"

deploy:
- provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
